FROM fwd-ubuntu-bionic:latest
MAINTAINER Jiri Helebrant <helb@helb.cz>
# whatever is required for building should be installed in this image; just like BuildDeps for DEB projects.
RUN apt-get update ; apt-get -y install rsync libreadline-dev libreadline7
